//----------------------------------------------------------------------------
// OWL File Extensions (OWLFX) Class Library
// OWL NExt Project
//
//$Revision: 1.1.4.2 $
//$Author: jogybl $
//$Date: 2009-10-23 10:49:38 $
//
//  OVERVIEW
//  ~~~~~~~~
//  Class definition for DataBase Enabled Controls.
//  (Generated by OWL 6.x Class Expert for MS VC++, Version 1.5)
//----------------------------------------------------------------------------
#if !defined(OWLFX_DBCTRLS_H) // Sentry, use file only if it's not already included.
#define OWLFX_DBCTRLS_H

#if !defined(OWL_STATIC_H)
# include <owl/static.h>
#endif
#if !defined(OWL_EDIT_H)
#	include <owl/edit.h>
#endif
#if !defined(OWL_DATETIME_H)
# include <owl/datetime.h>
#endif

#include <owlfx/defs.h>

#include <owlfx/abase.h>
#include <owlfx/previewd.h>

// this will be in OWL core 
#if !defined(MEMBER_METHOD_PROLOGUE)
#define MEMBER_METHOD_PROLOGUE(theClass, localClass, resultName) \
	theClass* resultName = \
		((theClass*)((BYTE*)this - offsetof(theClass, localClass))); \
	resultName; // avoid warning from compiler

#endif

_OWLFX_BEGIN_NAMESPACE


// Generic definitions/compiler options (eg. alignment) preceeding the
// definition of classes
#include <owl/preclass.h>

//{{TStatic = TDBFiledName}}
class _OWLFXCLASS TDBFiledName: public __OWL TStatic {
	typedef __OWL TStatic Inherited;
  public:
    TDBFiledName(__OWL TWindow* parent, int id, int fldId, TDBDataLink* link = 0, uint textLen = 0, __OWL TModule* module = 0);
		virtual void SetupWindow();

		void SetDBLink(TDBDataLink* link);

	protected:
		TDBDataLink*	DBLink;
		int						FieldId;
}; //{{TDBFiledName}}

//{{TStatic = TDBStatic}}
class _OWLFXCLASS TDBStatic: public __OWL TStatic {
	typedef __OWL TStatic Inherited;
  public:
    TDBStatic(__OWL TWindow* parent,int id, int fldId, TDBDataLink* link = 0, uint textLen = 0,__OWL TModule* module = 0);
		virtual void SetupWindow();
		virtual void CleanupWindow();

		struct TBDEvent: public TDBaseEvent{
			virtual long FireEvent(TType type, long p1 = 0, long p2 = 0);
		}DBEvent;
		friend struct TBDEvent;

		void SetDBLink(TDBDataLink* link);

	protected:
		TDBDataLink*	DBLink;
		int						FieldId;
}; //{{TDBStatic}}

//{{TStatic = TDBEdit}}
class _OWLFXCLASS TDBEdit: public __OWL TEdit {
	typedef __OWL TEdit Inherited;
  public:
    TDBEdit(__OWL TWindow* parent, int id, int fldId, TDBDataLink* link = 0, uint textLen = 0,__OWL TModule* module = 0);
		virtual void SetupWindow();
		virtual void CleanupWindow();

		struct TBDEvent: public TDBaseEvent{
			virtual long FireEvent(TType type, long p1 = 0, long p2 = 0);
		}DBEvent;
		friend struct TBDEvent;

		void SetDBLink(TDBDataLink* link);

	protected:
		TDBDataLink*	DBLink;
		int						FieldId;
}; //{{TDBEdit}}

//{{TStatic = TDBEdit}}
class _OWLFXCLASS TDBBlobEdit: public __OWL TEdit {
	typedef __OWL TEdit Inherited;
  public:
    TDBBlobEdit(__OWL TWindow* parent,int id, int fldId, TDBDataLink* link = 0, uint textLen = 0,__OWL TModule* module = 0);
		virtual void SetupWindow();
		virtual void CleanupWindow();

		struct TBDEvent: public TDBaseEvent{
			virtual long FireEvent(TType type, long p1 = 0, long p2 = 0);
		}DBEvent;
		friend struct TBDEvent;
	
		void SetDBLink(TDBDataLink* link);

	protected:
		TDBDataLink*	DBLink;
		int						FieldId;
}; //{{TDBBlobEdit}}

//{{TDateTimePicker = TDBDate}}
class _OWLFXCLASS TDBDate: public __OWL TDateTimePicker {
	typedef __OWL TDateTimePicker Inherited;
  public:
    TDBDate(__OWL TWindow* parent,int id,int fldId, TDBDataLink* link = 0, __OWL TModule* module = 0);
		virtual void SetupWindow();
		virtual void CleanupWindow();

		struct TBDEvent: public TDBaseEvent{
			virtual long FireEvent(TType type, long p1 = 0, long p2 = 0);
		}DBEvent;
		friend struct TBDEvent;

		void SetDBLink(TDBDataLink* link);

	protected:
		TDBDataLink*	DBLink;
		int						FieldId;
}; //{{TDBDate}}


//{{TDateTimePicker = TDBTime}}
class _OWLFXCLASS TDBTime: public __OWL TDateTimePicker {
	typedef __OWL TDateTimePicker Inherited;
  public:
    TDBTime(__OWL TWindow* parent, int id, int fldId, TDBDataLink* link = 0, __OWL TModule* module = 0);
		virtual void SetupWindow();
		virtual void CleanupWindow();

		struct TBDEvent: public TDBaseEvent{
			virtual long FireEvent(TType type, long p1 = 0, long p2 = 0);
		}DBEvent;
		friend struct TBDEvent;

		void SetDBLink(TDBDataLink* link);

	protected:
		TDBDataLink*	DBLink;
		int						FieldId;
}; //{{TDBTime}}

//{{TPictureControl = TDBBlobImage}}
class _OWLFXCLASS TDBBlobImage: public TPictureControl {
	typedef TPictureControl Inherited;
  public:
    TDBBlobImage(__OWL TWindow* parent,int id, int fldId, TDBDataLink* link = 0, __OWL TModule* module = 0);
		virtual void SetupWindow();
		virtual void CleanupWindow();

		struct TBDEvent: public TDBaseEvent{
			virtual long FireEvent(TType type, long p1 = 0, long p2 = 0);
		}DBEvent;
		friend struct TBDEvent;
	
		void SetDBLink(TDBDataLink* link);

	protected:
		TDBDataLink*	DBLink;
		int						FieldId;
}; //{{TDBBlobImage}}

// Generic definitions/compiler options (eg. alignment) following the
// definition of classes
#include <owl/posclass.h>


_OWLFX_END_NAMESPACE

#endif  // OWLFX_DBCTRLS_H sentry.

