/* version.rc 1: */
/* version.rc 2: */
/* version.rc 3: */
/* version.rc 4: */
/* version.rc 5: */
/* version.rc 6: */
/* version.rc 7: */
/* version.rc 8: */
/* version.rc 9: */
/* version.rc 10: */
/* version.rc 11: */
/* version.rc 12: */

/* C:\Tools\Borland\BCC55\Include\winver.h 1: */

/* C:\Tools\Borland\BCC55\Include\winver.h 2: */
/* C:\Tools\Borland\BCC55\Include\winver.h 3: */
/* C:\Tools\Borland\BCC55\Include\winver.h 4: */
/* C:\Tools\Borland\BCC55\Include\winver.h 5: */
/* C:\Tools\Borland\BCC55\Include\winver.h 6: */
/* C:\Tools\Borland\BCC55\Include\winver.h 7: */
/* C:\Tools\Borland\BCC55\Include\winver.h 8: */
/* C:\Tools\Borland\BCC55\Include\winver.h 9: */
/* C:\Tools\Borland\BCC55\Include\winver.h 10: */
/* C:\Tools\Borland\BCC55\Include\winver.h 11: */
/* C:\Tools\Borland\BCC55\Include\winver.h 12: */

/* C:\Tools\Borland\BCC55\Include\winver.h 13: */

/* C:\Tools\Borland\BCC55\Include\winver.h 14: */#pragma option push -b -a8 -pc -A- 
/* C:\Tools\Borland\BCC55\Include\winver.h 15: */
/* C:\Tools\Borland\BCC55\Include\winver.h 16: */
/* C:\Tools\Borland\BCC55\Include\winver.h 17: */
/* C:\Tools\Borland\BCC55\Include\winver.h 18: */
/* C:\Tools\Borland\BCC55\Include\winver.h 19: */
/* C:\Tools\Borland\BCC55\Include\winver.h 20: */
/* C:\Tools\Borland\BCC55\Include\winver.h 21: */
/* C:\Tools\Borland\BCC55\Include\winver.h 22: */
/* C:\Tools\Borland\BCC55\Include\winver.h 23: */
/* C:\Tools\Borland\BCC55\Include\winver.h 24: */
/* C:\Tools\Borland\BCC55\Include\winver.h 25: */
/* C:\Tools\Borland\BCC55\Include\winver.h 26: */
/* C:\Tools\Borland\BCC55\Include\winver.h 27: */
/* C:\Tools\Borland\BCC55\Include\winver.h 28: */
/* C:\Tools\Borland\BCC55\Include\winver.h 29: */
/* C:\Tools\Borland\BCC55\Include\winver.h 30: */
/* C:\Tools\Borland\BCC55\Include\winver.h 31: */
/* C:\Tools\Borland\BCC55\Include\winver.h 32: */
/* C:\Tools\Borland\BCC55\Include\winver.h 33: */
/* C:\Tools\Borland\BCC55\Include\winver.h 34: */
/* C:\Tools\Borland\BCC55\Include\winver.h 35: */
/* C:\Tools\Borland\BCC55\Include\winver.h 36: */
/* C:\Tools\Borland\BCC55\Include\winver.h 37: */
/* C:\Tools\Borland\BCC55\Include\winver.h 38: */
/* C:\Tools\Borland\BCC55\Include\winver.h 39: */
/* C:\Tools\Borland\BCC55\Include\winver.h 40: */
/* C:\Tools\Borland\BCC55\Include\winver.h 41: */
/* C:\Tools\Borland\BCC55\Include\winver.h 42: */
/* C:\Tools\Borland\BCC55\Include\winver.h 43: */
/* C:\Tools\Borland\BCC55\Include\winver.h 44: */
/* C:\Tools\Borland\BCC55\Include\winver.h 45: */
/* C:\Tools\Borland\BCC55\Include\winver.h 46: */
/* C:\Tools\Borland\BCC55\Include\winver.h 47: */
/* C:\Tools\Borland\BCC55\Include\winver.h 48: */
/* C:\Tools\Borland\BCC55\Include\winver.h 49: */
/* C:\Tools\Borland\BCC55\Include\winver.h 50: */
/* C:\Tools\Borland\BCC55\Include\winver.h 51: */
/* C:\Tools\Borland\BCC55\Include\winver.h 52: */
/* C:\Tools\Borland\BCC55\Include\winver.h 53: */
/* C:\Tools\Borland\BCC55\Include\winver.h 54: */
/* C:\Tools\Borland\BCC55\Include\winver.h 55: */
/* C:\Tools\Borland\BCC55\Include\winver.h 56: */
/* C:\Tools\Borland\BCC55\Include\winver.h 57: */
/* C:\Tools\Borland\BCC55\Include\winver.h 58: */
/* C:\Tools\Borland\BCC55\Include\winver.h 59: */
/* C:\Tools\Borland\BCC55\Include\winver.h 60: */
/* C:\Tools\Borland\BCC55\Include\winver.h 61: */
/* C:\Tools\Borland\BCC55\Include\winver.h 62: */
/* C:\Tools\Borland\BCC55\Include\winver.h 63: */
/* C:\Tools\Borland\BCC55\Include\winver.h 64: */
/* C:\Tools\Borland\BCC55\Include\winver.h 65: */
/* C:\Tools\Borland\BCC55\Include\winver.h 66: */
/* C:\Tools\Borland\BCC55\Include\winver.h 67: */
/* C:\Tools\Borland\BCC55\Include\winver.h 68: */
/* C:\Tools\Borland\BCC55\Include\winver.h 69: */
/* C:\Tools\Borland\BCC55\Include\winver.h 70: */
/* C:\Tools\Borland\BCC55\Include\winver.h 71: */
/* C:\Tools\Borland\BCC55\Include\winver.h 72: */
/* C:\Tools\Borland\BCC55\Include\winver.h 73: */
/* C:\Tools\Borland\BCC55\Include\winver.h 74: */
/* C:\Tools\Borland\BCC55\Include\winver.h 75: */
/* C:\Tools\Borland\BCC55\Include\winver.h 76: */
/* C:\Tools\Borland\BCC55\Include\winver.h 77: */
/* C:\Tools\Borland\BCC55\Include\winver.h 78: */
/* C:\Tools\Borland\BCC55\Include\winver.h 79: */
/* C:\Tools\Borland\BCC55\Include\winver.h 80: */
/* C:\Tools\Borland\BCC55\Include\winver.h 81: */
/* C:\Tools\Borland\BCC55\Include\winver.h 82: */
/* C:\Tools\Borland\BCC55\Include\winver.h 83: */
/* C:\Tools\Borland\BCC55\Include\winver.h 84: */
/* C:\Tools\Borland\BCC55\Include\winver.h 85: */
/* C:\Tools\Borland\BCC55\Include\winver.h 86: */
/* C:\Tools\Borland\BCC55\Include\winver.h 87: */
/* C:\Tools\Borland\BCC55\Include\winver.h 88: */
/* C:\Tools\Borland\BCC55\Include\winver.h 89: */
/* C:\Tools\Borland\BCC55\Include\winver.h 90: */
/* C:\Tools\Borland\BCC55\Include\winver.h 91: */
/* C:\Tools\Borland\BCC55\Include\winver.h 92: */
/* C:\Tools\Borland\BCC55\Include\winver.h 93: */
/* C:\Tools\Borland\BCC55\Include\winver.h 94: */
/* C:\Tools\Borland\BCC55\Include\winver.h 95: */
/* C:\Tools\Borland\BCC55\Include\winver.h 96: */
/* C:\Tools\Borland\BCC55\Include\winver.h 97: */
/* C:\Tools\Borland\BCC55\Include\winver.h 98: */
/* C:\Tools\Borland\BCC55\Include\winver.h 99: */
/* C:\Tools\Borland\BCC55\Include\winver.h 100: */
/* C:\Tools\Borland\BCC55\Include\winver.h 101: */
/* C:\Tools\Borland\BCC55\Include\winver.h 102: */
/* C:\Tools\Borland\BCC55\Include\winver.h 103: */
/* C:\Tools\Borland\BCC55\Include\winver.h 104: */
/* C:\Tools\Borland\BCC55\Include\winver.h 105: */
/* C:\Tools\Borland\BCC55\Include\winver.h 106: */
/* C:\Tools\Borland\BCC55\Include\winver.h 107: */
/* C:\Tools\Borland\BCC55\Include\winver.h 108: */
/* C:\Tools\Borland\BCC55\Include\winver.h 109: */
/* C:\Tools\Borland\BCC55\Include\winver.h 110: */
/* C:\Tools\Borland\BCC55\Include\winver.h 111: */
/* C:\Tools\Borland\BCC55\Include\winver.h 112: */
/* C:\Tools\Borland\BCC55\Include\winver.h 113: */
/* C:\Tools\Borland\BCC55\Include\winver.h 114: */
/* C:\Tools\Borland\BCC55\Include\winver.h 115: */
/* C:\Tools\Borland\BCC55\Include\winver.h 116: */
/* C:\Tools\Borland\BCC55\Include\winver.h 117: */
/* C:\Tools\Borland\BCC55\Include\winver.h 118: */
/* C:\Tools\Borland\BCC55\Include\winver.h 119: */
/* C:\Tools\Borland\BCC55\Include\winver.h 120: */
/* C:\Tools\Borland\BCC55\Include\winver.h 121: */
/* C:\Tools\Borland\BCC55\Include\winver.h 122: */
/* C:\Tools\Borland\BCC55\Include\winver.h 123: */
/* C:\Tools\Borland\BCC55\Include\winver.h 124: */
/* C:\Tools\Borland\BCC55\Include\winver.h 125: */
/* C:\Tools\Borland\BCC55\Include\winver.h 126: */
/* C:\Tools\Borland\BCC55\Include\winver.h 127: */
/* C:\Tools\Borland\BCC55\Include\winver.h 128: */
/* C:\Tools\Borland\BCC55\Include\winver.h 129: */
/* C:\Tools\Borland\BCC55\Include\winver.h 130: */
/* C:\Tools\Borland\BCC55\Include\winver.h 131: */
/* C:\Tools\Borland\BCC55\Include\winver.h 132: */
/* C:\Tools\Borland\BCC55\Include\winver.h 133: */
/* C:\Tools\Borland\BCC55\Include\winver.h 134: */
/* C:\Tools\Borland\BCC55\Include\winver.h 135: */
/* C:\Tools\Borland\BCC55\Include\winver.h 136: */
/* C:\Tools\Borland\BCC55\Include\winver.h 137: */
/* C:\Tools\Borland\BCC55\Include\winver.h 138: */
/* C:\Tools\Borland\BCC55\Include\winver.h 139: */
/* C:\Tools\Borland\BCC55\Include\winver.h 140: */
/* C:\Tools\Borland\BCC55\Include\winver.h 141: */
/* C:\Tools\Borland\BCC55\Include\winver.h 142: */
/* C:\Tools\Borland\BCC55\Include\winver.h 143: */
/* C:\Tools\Borland\BCC55\Include\winver.h 144: */
/* C:\Tools\Borland\BCC55\Include\winver.h 145: */
/* C:\Tools\Borland\BCC55\Include\winver.h 146: */
/* C:\Tools\Borland\BCC55\Include\winver.h 147: */
/* C:\Tools\Borland\BCC55\Include\winver.h 148: */
/* C:\Tools\Borland\BCC55\Include\winver.h 149: */
/* C:\Tools\Borland\BCC55\Include\winver.h 150: */
/* C:\Tools\Borland\BCC55\Include\winver.h 151: */
/* C:\Tools\Borland\BCC55\Include\winver.h 152: */
/* C:\Tools\Borland\BCC55\Include\winver.h 153: */
/* C:\Tools\Borland\BCC55\Include\winver.h 154: */
/* C:\Tools\Borland\BCC55\Include\winver.h 155: */
/* C:\Tools\Borland\BCC55\Include\winver.h 156: */
/* C:\Tools\Borland\BCC55\Include\winver.h 157: */
/* C:\Tools\Borland\BCC55\Include\winver.h 158: */
/* C:\Tools\Borland\BCC55\Include\winver.h 159: */
/* C:\Tools\Borland\BCC55\Include\winver.h 160: */
/* C:\Tools\Borland\BCC55\Include\winver.h 161: */
/* C:\Tools\Borland\BCC55\Include\winver.h 162: */
/* C:\Tools\Borland\BCC55\Include\winver.h 163: */
/* C:\Tools\Borland\BCC55\Include\winver.h 164: */
/* C:\Tools\Borland\BCC55\Include\winver.h 165: */
/* C:\Tools\Borland\BCC55\Include\winver.h 166: */
/* C:\Tools\Borland\BCC55\Include\winver.h 167: */
/* C:\Tools\Borland\BCC55\Include\winver.h 168: */
/* C:\Tools\Borland\BCC55\Include\winver.h 169: */
/* C:\Tools\Borland\BCC55\Include\winver.h 170: */
/* C:\Tools\Borland\BCC55\Include\winver.h 171: */
/* C:\Tools\Borland\BCC55\Include\winver.h 172: */
/* C:\Tools\Borland\BCC55\Include\winver.h 173: */
/* C:\Tools\Borland\BCC55\Include\winver.h 174: */
/* C:\Tools\Borland\BCC55\Include\winver.h 175: */
/* C:\Tools\Borland\BCC55\Include\winver.h 176: */
/* C:\Tools\Borland\BCC55\Include\winver.h 177: */
/* C:\Tools\Borland\BCC55\Include\winver.h 178: */
/* C:\Tools\Borland\BCC55\Include\winver.h 179: */
/* C:\Tools\Borland\BCC55\Include\winver.h 180: */
/* C:\Tools\Borland\BCC55\Include\winver.h 181: */
/* C:\Tools\Borland\BCC55\Include\winver.h 182: */
/* C:\Tools\Borland\BCC55\Include\winver.h 183: */
/* C:\Tools\Borland\BCC55\Include\winver.h 184: */
/* C:\Tools\Borland\BCC55\Include\winver.h 185: */
/* C:\Tools\Borland\BCC55\Include\winver.h 186: */
/* C:\Tools\Borland\BCC55\Include\winver.h 187: */
/* C:\Tools\Borland\BCC55\Include\winver.h 188: */
/* C:\Tools\Borland\BCC55\Include\winver.h 189: */
/* C:\Tools\Borland\BCC55\Include\winver.h 190: */
/* C:\Tools\Borland\BCC55\Include\winver.h 191: */
/* C:\Tools\Borland\BCC55\Include\winver.h 192: */
/* C:\Tools\Borland\BCC55\Include\winver.h 193: */
/* C:\Tools\Borland\BCC55\Include\winver.h 194: */
/* C:\Tools\Borland\BCC55\Include\winver.h 195: */
/* C:\Tools\Borland\BCC55\Include\winver.h 196: */
/* C:\Tools\Borland\BCC55\Include\winver.h 197: */
/* C:\Tools\Borland\BCC55\Include\winver.h 198: */
/* C:\Tools\Borland\BCC55\Include\winver.h 199: */
/* C:\Tools\Borland\BCC55\Include\winver.h 200: */
/* C:\Tools\Borland\BCC55\Include\winver.h 201: */
/* C:\Tools\Borland\BCC55\Include\winver.h 202: */
/* C:\Tools\Borland\BCC55\Include\winver.h 203: */
/* C:\Tools\Borland\BCC55\Include\winver.h 204: */
/* C:\Tools\Borland\BCC55\Include\winver.h 205: */
/* C:\Tools\Borland\BCC55\Include\winver.h 206: */
/* C:\Tools\Borland\BCC55\Include\winver.h 207: */
/* C:\Tools\Borland\BCC55\Include\winver.h 208: */
/* C:\Tools\Borland\BCC55\Include\winver.h 209: */
/* C:\Tools\Borland\BCC55\Include\winver.h 210: */
/* C:\Tools\Borland\BCC55\Include\winver.h 211: */
/* C:\Tools\Borland\BCC55\Include\winver.h 212: */
/* C:\Tools\Borland\BCC55\Include\winver.h 213: */
/* C:\Tools\Borland\BCC55\Include\winver.h 214: */
/* C:\Tools\Borland\BCC55\Include\winver.h 215: */
/* C:\Tools\Borland\BCC55\Include\winver.h 216: */
/* C:\Tools\Borland\BCC55\Include\winver.h 217: */
/* C:\Tools\Borland\BCC55\Include\winver.h 218: */
/* C:\Tools\Borland\BCC55\Include\winver.h 219: */
/* C:\Tools\Borland\BCC55\Include\winver.h 220: */
/* C:\Tools\Borland\BCC55\Include\winver.h 221: */
/* C:\Tools\Borland\BCC55\Include\winver.h 222: */
/* C:\Tools\Borland\BCC55\Include\winver.h 223: */
/* C:\Tools\Borland\BCC55\Include\winver.h 224: */
/* C:\Tools\Borland\BCC55\Include\winver.h 225: */
/* C:\Tools\Borland\BCC55\Include\winver.h 226: */
/* C:\Tools\Borland\BCC55\Include\winver.h 227: */
/* C:\Tools\Borland\BCC55\Include\winver.h 228: */
/* C:\Tools\Borland\BCC55\Include\winver.h 229: */
/* C:\Tools\Borland\BCC55\Include\winver.h 230: */
/* C:\Tools\Borland\BCC55\Include\winver.h 231: */
/* C:\Tools\Borland\BCC55\Include\winver.h 232: */
/* C:\Tools\Borland\BCC55\Include\winver.h 233: */
/* C:\Tools\Borland\BCC55\Include\winver.h 234: */
/* C:\Tools\Borland\BCC55\Include\winver.h 235: */
/* C:\Tools\Borland\BCC55\Include\winver.h 236: */
/* C:\Tools\Borland\BCC55\Include\winver.h 237: */
/* C:\Tools\Borland\BCC55\Include\winver.h 238: */
/* C:\Tools\Borland\BCC55\Include\winver.h 239: */
/* C:\Tools\Borland\BCC55\Include\winver.h 240: */
/* C:\Tools\Borland\BCC55\Include\winver.h 241: */
/* C:\Tools\Borland\BCC55\Include\winver.h 242: */
/* C:\Tools\Borland\BCC55\Include\winver.h 243: */
/* C:\Tools\Borland\BCC55\Include\winver.h 244: */
/* C:\Tools\Borland\BCC55\Include\winver.h 245: */
/* C:\Tools\Borland\BCC55\Include\winver.h 246: */
/* C:\Tools\Borland\BCC55\Include\winver.h 247: */
/* C:\Tools\Borland\BCC55\Include\winver.h 248: */
/* C:\Tools\Borland\BCC55\Include\winver.h 249: */
/* C:\Tools\Borland\BCC55\Include\winver.h 250: */
/* C:\Tools\Borland\BCC55\Include\winver.h 251: */
/* C:\Tools\Borland\BCC55\Include\winver.h 252: */
/* C:\Tools\Borland\BCC55\Include\winver.h 253: */
/* C:\Tools\Borland\BCC55\Include\winver.h 254: */
/* C:\Tools\Borland\BCC55\Include\winver.h 255: */
/* C:\Tools\Borland\BCC55\Include\winver.h 256: */
/* C:\Tools\Borland\BCC55\Include\winver.h 257: */
/* C:\Tools\Borland\BCC55\Include\winver.h 258: */
/* C:\Tools\Borland\BCC55\Include\winver.h 259: */
/* C:\Tools\Borland\BCC55\Include\winver.h 260: */
/* C:\Tools\Borland\BCC55\Include\winver.h 261: */
/* C:\Tools\Borland\BCC55\Include\winver.h 262: */
/* C:\Tools\Borland\BCC55\Include\winver.h 263: */
/* C:\Tools\Borland\BCC55\Include\winver.h 264: */
/* C:\Tools\Borland\BCC55\Include\winver.h 265: */
/* C:\Tools\Borland\BCC55\Include\winver.h 266: */
/* C:\Tools\Borland\BCC55\Include\winver.h 267: */
/* C:\Tools\Borland\BCC55\Include\winver.h 268: */
/* C:\Tools\Borland\BCC55\Include\winver.h 269: */
/* C:\Tools\Borland\BCC55\Include\winver.h 270: */
/* C:\Tools\Borland\BCC55\Include\winver.h 271: */
/* C:\Tools\Borland\BCC55\Include\winver.h 272: */
/* C:\Tools\Borland\BCC55\Include\winver.h 273: */
/* C:\Tools\Borland\BCC55\Include\winver.h 274: */
/* C:\Tools\Borland\BCC55\Include\winver.h 275: */
/* C:\Tools\Borland\BCC55\Include\winver.h 276: */
/* C:\Tools\Borland\BCC55\Include\winver.h 277: */
/* C:\Tools\Borland\BCC55\Include\winver.h 278: */
/* C:\Tools\Borland\BCC55\Include\winver.h 279: */
/* C:\Tools\Borland\BCC55\Include\winver.h 280: */
/* C:\Tools\Borland\BCC55\Include\winver.h 281: */
/* C:\Tools\Borland\BCC55\Include\winver.h 282: */
/* C:\Tools\Borland\BCC55\Include\winver.h 283: */
/* C:\Tools\Borland\BCC55\Include\winver.h 284: */
/* C:\Tools\Borland\BCC55\Include\winver.h 285: */
/* C:\Tools\Borland\BCC55\Include\winver.h 286: */
/* C:\Tools\Borland\BCC55\Include\winver.h 287: */
/* C:\Tools\Borland\BCC55\Include\winver.h 288: */
/* C:\Tools\Borland\BCC55\Include\winver.h 289: */
/* C:\Tools\Borland\BCC55\Include\winver.h 290: */
/* C:\Tools\Borland\BCC55\Include\winver.h 291: */
/* C:\Tools\Borland\BCC55\Include\winver.h 292: */
/* C:\Tools\Borland\BCC55\Include\winver.h 293: */
/* C:\Tools\Borland\BCC55\Include\winver.h 294: */
/* C:\Tools\Borland\BCC55\Include\winver.h 295: */
/* C:\Tools\Borland\BCC55\Include\winver.h 296: */
/* C:\Tools\Borland\BCC55\Include\winver.h 297: */
/* C:\Tools\Borland\BCC55\Include\winver.h 298: */
/* C:\Tools\Borland\BCC55\Include\winver.h 299: */
/* C:\Tools\Borland\BCC55\Include\winver.h 300: */
/* C:\Tools\Borland\BCC55\Include\winver.h 301: */
/* C:\Tools\Borland\BCC55\Include\winver.h 302: */#pragma option pop 
/* C:\Tools\Borland\BCC55\Include\winver.h 303: */
/* C:\Tools\Borland\BCC55\Include\winver.h 304: */
/* C:\Tools\Borland\BCC55\Include\winver.h 305: */
/* C:\Tools\Borland\BCC55\Include\winver.h 306: */
/* version.rc 13: */
/* version.rc 14: */
/* version.rc 15: */
/* version.rc 16: */

/* D:\Work\OWLNext\630\Include\ocf/version.h 1: */

/* D:\Work\OWLNext\630\Include\ocf/version.h 2: */

/* D:\Work\OWLNext\630\Include\ocf/version.h 3: */

/* D:\Work\OWLNext\630\Include\ocf/version.h 4: */

/* D:\Work\OWLNext\630\Include\ocf/version.h 5: */

/* D:\Work\OWLNext\630\Include\ocf/version.h 6: */

/* D:\Work\OWLNext\630\Include\ocf/version.h 7: */

/* D:\Work\OWLNext\630\Include\ocf/version.h 8: */

/* D:\Work\OWLNext\630\Include\ocf/version.h 9: */

/* D:\Work\OWLNext\630\Include\ocf/version.h 10: */

/* D:\Work\OWLNext\630\Include\ocf/version.h 11: */

/* D:\Work\OWLNext\630\Include\ocf/version.h 12: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 13: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 14: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 15: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 16: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 17: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 18: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 19: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 20: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 21: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 22: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 23: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 24: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 25: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 26: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 27: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 28: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 29: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 30: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 31: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 32: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 33: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 34: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 35: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 36: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 37: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 38: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 39: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 40: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 41: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 42: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 43: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 44: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 45: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 46: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 47: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 48: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 49: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 50: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 51: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 52: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 53: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 54: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 55: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 56: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 57: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 58: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 59: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 60: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 61: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 62: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 63: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 64: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 65: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 66: */   
/* D:\Work\OWLNext\630\Include\ocf/version.h 67: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 68: */  
/* D:\Work\OWLNext\630\Include\ocf/version.h 69: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 70: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 71: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 72: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 73: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 74: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 75: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 76: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 77: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 78: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 79: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 80: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 81: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 82: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 83: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 84: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 85: */ 
/* D:\Work\OWLNext\630\Include\ocf/version.h 86: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 87: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 88: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 89: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 90: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 91: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 92: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 93: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 94: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 95: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 96: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 97: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 98: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 99: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 100: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 101: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 102: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 103: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 104: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 105: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 106: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 107: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 108: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 109: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 110: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 111: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 112: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 113: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 114: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 115: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 116: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 117: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 118: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 119: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 120: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 121: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 122: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 123: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 124: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 125: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 126: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 127: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 128: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 129: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 130: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 131: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 132: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 133: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 134: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 135: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 136: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 137: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 138: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 139: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 140: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 141: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 142: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 143: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 144: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 145: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 146: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 147: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 148: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 149: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 150: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 151: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 152: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 153: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 154: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 155: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 156: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 157: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 158: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 159: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 160: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 161: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 162: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 163: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 164: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 165: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 166: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 167: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 168: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 169: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 170: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 171: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 172: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 173: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 174: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 175: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 176: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 177: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 178: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 179: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 180: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 181: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 182: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 183: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 184: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 185: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 186: */
/* D:\Work\OWLNext\630\Include\ocf/version.h 187: */
/* version.rc 17: */
/* version.rc 18: */
/* version.rc 19: */
/* version.rc 20: */
/* version.rc 21: */
/* version.rc 22: */
/* version.rc 23: */
/* version.rc 24: */
/* version.rc 25: */
/* version.rc 26: */1 VERSIONINFO
/* version.rc 27: */FILEVERSION     6, 30, 9, 902
/* version.rc 28: */FILEFLAGS       0x00000002L | 0x00000020L | 0x00000001L
/* version.rc 29: */FILEFLAGSMASK   0x00000020L
/* version.rc 30: */
/* version.rc 31: */FILEOS          0x00000004L
/* version.rc 32: */
/* version.rc 33: */
/* version.rc 34: */
/* version.rc 35: */PRODUCTVERSION  6, 30, 9, 902
/* version.rc 36: */FILETYPE        0x00000002L
/* version.rc 37: */BEGIN
/* version.rc 38: */BLOCK "StringFileInfo"
/* version.rc 39: */BEGIN
/* version.rc 40: */BLOCK "040904E4"
/* version.rc 41: */BEGIN
/* version.rc 42: */VALUE "CompanyName", "Borland International & OCFNext\0"
/* version.rc 43: */VALUE "URL", "www.owlnext.org\0"
/* version.rc 44: */VALUE "FileDescription", "Object Components Library \0"
/* version.rc 45: */VALUE "FileVersion", "6" "." "30" "." "9" "." "902" "\0"
/* version.rc 46: */VALUE "InternalName", "OCF" "6" "30" "DF" "\0"
/* version.rc 47: */VALUE "LegalCopyright", "Copyright © Borland International 1991,1996, Yura Bidus 1998, Jogy 2004-2006\0"
/* version.rc 48: */VALUE "ProductName", "ObjectComponents\0"
/* version.rc 49: */VALUE "ProductVersion", "6" "." "30" "\0"
/* version.rc 50: */END
/* version.rc 51: */END
/* version.rc 52: */BLOCK "VarFileInfo"
/* version.rc 53: */BEGIN                               
/* version.rc 54: */VALUE "Translation", 0x409, 0x4E4 
/* version.rc 55: */END
/* version.rc 56: */END
/* version.rc 57: */
/* version.rc 58: */