//----------------------------------------------------------------------------
//  Project dview
//  Some Company
//  Copyright 1999. All Rights reserved.
//
//  SUBSYSTEM:    dview Application
//  FILE:         dviewapp.h
//  AUTHOR:       Author
//
//  OVERVIEW
//  ~~~~~~~~
//  Class definition for TdviewAppl (TApplication).
//  (Generated by OWL 6.0 Wizard for MS VC++. Version 1.5)
//----------------------------------------------------------------------------
#if !defined(dviewapp_h) // Sentry, use file only if it's not already included.
#define dviewapp_h

#include <owl/decframe.h>

#include "resource.h"            // Definition of all resources.


//
// FrameWindow must be derived to override Paint for Preview and Print.
//
//{{TFrameWindow = TSDIFrameWindow}}
class TSDIFrameWindow : public TFrameWindow {
  public:
    TSDIFrameWindow(TWindow* parent, LPCTSTR title, TWindow* clientWnd = 0, bool shrinkToClient = false, TModule* module = 0);
    ~TSDIFrameWindow();

};    //{{TSDIFrameWindow}}

//{{TApplication = TdviewAppl}}
class TdviewAppl : public TApplication {
  private:

  public:
    TdviewAppl();
    virtual ~TdviewAppl();

//{{TdviewApplVIRTUAL_BEGIN}}
  public:
    virtual void InitMainWindow();
    virtual void InitInstance();
//{{TdviewApplVIRTUAL_END}}

//{{TdviewApplRSP_TBL_BEGIN}}
  protected:
    void EvNewView(TView& view);
    void EvCloseView(TView& view);
//{{TdviewApplRSP_TBL_END}}
DECLARE_RESPONSE_TABLE(TdviewAppl);
};    //{{TdviewAppl}}


#endif  // dviewapp_h sentry.
