//----------------------------------------------------------------------------
//  Project dview
//  Some Company
//  Copyright 1999. All Rights reserved.
//
//  SUBSYSTEM:    dview Application
//  FILE:         dviewcl.cpp
//  AUTHOR:       Author
//
//  OVERVIEW
//  ~~~~~~~~
//  Source file for implementation of TdviewView (TDialogView).
//  (Generated by OWL 6.x Wizard for MS VC++. Version 1.5)
//----------------------------------------------------------------------------
#include "owlpch.h"

#include <owl\treewind.h>

#include "dviewapp.h"
#include "dviewcl.h" // Definition of client class.


//{{TdviewView Implementation}}


//--------------------------------------------------------
// TdviewView
// ~~~~~~~~~~
// Construction/Destruction handling.
//
TdviewView::TdviewView(TDocument& doc, TWindow* parent)
:
  TDialogView(doc, parent, IDD_CLIENT)
{
//{{TdviewViewXFER_USE}}
		TreeWindTree1 = new TTreeWindow(this, IDC_TREE1);
//{{TdviewViewXFER_USE_END}}
  // INSERT>> Your constructor code here.
}
//
TdviewView::~TdviewView()
{
  // INSERT>> Your destructor code here.
}
//


void TdviewView::SetupWindow()
{	
	// Call base class function.
	TDialog::SetupWindow();

	// INSERT>> Your code here.
  // Initialize TreeWind
  //
  TTreeNode root = TreeWindTree1->GetRoot();
  root.AddChild(TTreeNode(*TreeWindTree1, "Child 8"));

  TTreeNode parent1 = root.AddChild(TTreeNode(*TreeWindTree1, "Parent 1"));
  TTreeNode child1  = parent1.AddChild(TTreeNode(*TreeWindTree1, "Child 1"));
                      parent1.AddChild(TTreeNode(*TreeWindTree1, "Child 2 (with some longer text)"));

  root.AddChild(TTreeNode(*TreeWindTree1, "Child 0"));

  TTreeNode parent2 = root.AddChild(TTreeNode(*TreeWindTree1, "Parent 2"));
            parent2.AddChild(TTreeNode(*TreeWindTree1, "Child 3"));
            parent2.AddChild(TTreeNode(*TreeWindTree1, "Child 4"));

  TTreeNode subParent1 = child1.InsertItem(TTreeNode(*TreeWindTree1, "Subparent 1"));
            subParent1.AddChild(TTreeNode(*TreeWindTree1, "Child 5"));
            subParent1.AddChild(TTreeNode(*TreeWindTree1, "Child 6"));

  root.AddChild(TTreeNode(*TreeWindTree1, "Child 7"));

  TreeWindTree1->Update();
  
	parent2.ExpandItem(TVE_EXPAND);
}
//
