//----------------------------------------------------------------------------
//  Project dview
//  Some Company
//  Copyright 1999. All Rights reserved.
//
//  SUBSYSTEM:    dview Application
//  FILE:         dviewcl.h
//  AUTHOR:       Author
//
//  OVERVIEW
//  ~~~~~~~~
//  Class definition for TdviewView (TDialog).
//  (Generated by OWL 6.0 Wizard for MS VC++. Version 1.5)
//----------------------------------------------------------------------------
#if !defined(dviewcl_h) // Sentry, use file only if it's not already included.
#define dviewcl_h

#include <owl/docview.h>
#include "resource.h"                  // Definition of all resources.

__OWL_DECLCLASS(TTreeWindow);

//{{TDialogView = TdviewView}}
class TdviewView : public TDialogView {
  public:
    TdviewView(TDocument& doc, TWindow* parent=0);
    virtual ~TdviewView();

//{{TdviewViewXFER_DEF}}
	protected:
		TTreeWindow*	TreeWindTree1;
//{{TdviewViewXFER_DEF_END}}

//{{TdviewViewVIRTUAL_BEGIN}}
	public:
		virtual void SetupWindow();
//{{TdviewViewVIRTUAL_END}}

};    //{{TdviewView}}

#endif  // dviewcl_h sentry.
