#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1996, 1996 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

MODELS = df

EXERES = tooltip
OBJEXE = tooltipx.obj

!ifndef OWLROOT
!include ..\..\..\source\owlroot.inc
!endif
!include $(OWLROOT)\examples\owlmake.gen
