#----------------------------------------------------------------------------
# ObjectWindows - (c) Copyright 1996 by Borland International
#----------------------------------------------------------------------------

MODELS   = fd
EXE      = replace+
DEFEXE   = ReplacePlus.def
OBJEXE   = app.obj client.obj help.obj replacer.obj util.obj

!ifndef OWLROOT
!include ..\..\..\source\owlroot.inc
!endif
!include $(OWLROOT)\examples\owlmake.gen

