//----------------------------------------------------------------------------
//  Project odlistm
//  My Copmany
//  Copyright 1998. All right reserved.
//
//  SUBSYSTEM:    odlistm Application
//  FILE:         odlistmcl.cpp
//  AUTHOR:       Author
//
//  OVERVIEW
//  ~~~~~~~~
//  Source file for implementation of TodlistmView (TEditFile).
//  (Generated by OWL 6.0 Wizard for VC.)
//----------------------------------------------------------------------------
#include "owlpch.h"

#include "odlistmapp.h"
#include "odlistmcl.h"

#include <stdio.h>


//{{TodlistmView Implementation}}


//--------------------------------------------------------
// TodlistmView
// ~~~~~~~~~~
// Construction/Destruction handling.
//
TodlistmView::TodlistmView(TWindow* parent, int id, LPCTSTR text, int x, int y, int w, int h, LPCTSTR fileName, TModule* module)
:
  TEditFile(parent, id, text, x, y, w, h, fileName, module)
{
  // INSERT>> Your constructor code here.

}


TodlistmView::~TodlistmView()
{
  Destroy();

  // INSERT>> Your destructor code here.

}


void TodlistmView::SetupWindow()
{
  TEditFile::SetupWindow();

  TodlistmAppl* theApp = TYPESAFE_DOWNCAST(GetApplication(), TodlistmAppl);
  FileData = theApp->FileData;
}
