//----------------------------------------------------------------------------
//  Project odlistm
//  My Copmany
//  Copyright 1998. All right reserved.
//
//  SUBSYSTEM:    odlistm Application
//  FILE:         odlistmab.h
//  AUTHOR:       Author
//
//  OVERVIEW
//  ~~~~~~~~
//  Class definition for TodlistmAboutDlg (TDialog).
//  (Generated by OWL 6.0 Wizard for VC.)
//----------------------------------------------------------------------------
#if !defined(odlistmab_h)              // Sentry, use file only if it's not already included.
#define odlistmab_h

#include <owl/static.h>

#include "resource.h"                  // Definition of all resources.


//{{TDialog = TodlistmAboutDlg}}
class TodlistmAboutDlg : public TDialog {
  public:
    TodlistmAboutDlg(TWindow* parent, TResId resId = IDD_ABOUTDLG, TModule* module = 0);
    virtual ~TodlistmAboutDlg();

//{{TodlistmAboutDlgVIRTUAL_BEGIN}}
  public:
    void SetupWindow();
//{{TodlistmAboutDlgVIRTUAL_END}}
};    //{{TodlistmAboutDlg}}


// Reading the VERSIONINFO resource.
//
class TProjectRCVersion {
  public:
    TProjectRCVersion(TModule* module);
    virtual ~TProjectRCVersion();

    bool GetProductName(LPSTR& prodName);
    bool GetProductVersion(LPSTR& prodVersion);
    bool GetCopyright(LPSTR& copyright);
    bool GetDebug(LPSTR& debug);

  protected:
    uint8 far*  TransBlock;
    void far*   FVData;

  private:
    // Don't allow this object to be copied.
    //
    TProjectRCVersion(const TProjectRCVersion&);
    TProjectRCVersion& operator = (const TProjectRCVersion&);
};

#endif  // odlistmab_h sentry.
