//----------------------------------------------------------------------------
//  Project odlistm
//  My Copmany
//  Copyright 1998. All right reserved.
//
//  SUBSYSTEM:    odlistm Application
//  FILE:         odlistmcl.h
//  AUTHOR:       Author
//
//  OVERVIEW
//  ~~~~~~~~
//  Class definition for TodlistmView (TEditFile).
//  (Generated by OWL 6.0 Wizard for VC.)
//----------------------------------------------------------------------------
#if !defined(odlistmcl_h)              // Sentry, use file only if it's not already included.
#define odlistmcl_h

#include <owl/editfile.h>

#include "resource.h"            // Definition of all resources.


//{{TEditFile = TodlistmView}}
class TodlistmView : public TEditFile {
  public:
    TodlistmView(TWindow* parent = 0, int id = 0, LPCTSTR text = 0, int x = 0, int y = 0, int w = 0, int h = 0, LPCTSTR fileName = 0, TModule* module = 0);
    virtual ~TodlistmView();
//{{TodlistmViewVIRTUAL_BEGIN}}
  public:
    virtual void SetupWindow();
//{{TodlistmViewVIRTUAL_END}}
};    //{{TodlistmView}}

#endif  // odlistmcl_h sentry.
