#----------------------------------------------------------------------------
# ObjectWindows
# Copyright (c) 1991, 1995 by Borland International, All Rights Reserved
#----------------------------------------------------------------------------

EXERES=bmpview
MODELS=df

!ifndef OWLROOT
!include ..\..\..\source\owlroot.inc
!endif
!include $(OWLROOT)\examples\owlmake.gen

